name: relayai-semantic-search
services:
  mongodb:
    image: mongodb/mongodb-atlas-local:8.0@sha256:1985314b0ded756ba965e0f400d17406b7a89bec659d4763a490f42f006e4fbd
    hostname: mongodb
    ports:
      - "127.0.0.1:27019:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
      - mongo_search:/data/mongot
    cpus: 2
    mem_limit: 3g
volumes:
  mongo_data:
  mongo_config:
  mongo_search:
